title: Unity AI CoPilot
description: The Autonomous AI Agent for Unity that codes, fixes, and creates for you.
remote_theme: just-the-docs/just-the-docs

url: https://decnet-games.github.io
baseurl: /UnityAiCopilot-Doc

color_scheme: dark

aux_links:
  GitHub Repository: https://github.com/DecNet-Games/UnityAICoPilot

enable_search_in_sidebar: true

# Footer content
footer_content: "Â© 2026 DecNet Games. All rights reserved."
